### ISSUE TITLE
멋진 설명과 코드 감사드립니다

### ISSUE THREAD

**Issue by goonbamm** [lovit/pagerank#1]
학부생으로서 이해가 잘되서 정말 감사드립니다
그런데 설명하신 걸 읽어보니 각 영화별 리뷰를 정리하신 데이터가 있다고 하던데 올려주실 수 있을까요?

다시 한번 이렇게 공유뿐만 아니라 멋진 설명에 감사를 표합니다.

**Comment by lovit** [comment]
살펴보니 해당 데이터가 빠져 있었네요. 업로드 해뒀습니다.
